import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from '@/components/Navbar';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import { config } from '../../config';
import { ContextProvider } from '../../context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'BitStart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ContextProvider initialState={initialState}>
            <Navbar />
            {children}
          </ContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
